# Generated by Django 2.2.2 on 2019-06-22 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('bio', models.CharField(help_text='Enter a short biography.', max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('name', models.CharField(help_text='Enter name for blog post.', max_length=122)),
                ('content', models.TextField(help_text='Enter content of blog post.')),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogsite.Blogger')),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.CharField(help_text='Enter comment.', max_length=256)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogsite.BlogPost')),
            ],
            options={
                'ordering': ['date'],
                'permissions': (('can_comment', 'User can comment on posts'),),
            },
        ),
    ]
