# Generated by Django 2.2.2 on 2019-06-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_comment_commenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-post_date']},
        ),
    ]
